# As there is (still) no Travis Lua language support, we use the fine
# https://github.com/mpeterv/hererocks local environment build to set
# up a local Lua/luarocks/packages environment.
language: python
python: 3.7
sudo: false

branches:
  only:
    - /.*/

install:
  - ./env.sh # installs the local environment.

script:
  - ./env.sh busted # runs all tests.
